name: Weekly PubMed Scraper

on:
  schedule:
    # 17:00 UTC Friday = 13:00 ET (NYC)
    - cron: "0 17 * * FRI"
  workflow_dispatch: {}

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install deps
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run scraper
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          EMAIL_USER:      ${{ secrets.EMAIL_USER }}
          EMAIL_PASS:      ${{ secrets.EMAIL_PASS }}
          NCBI_KEY:        ${{ secrets.NCBI_KEY }}
        run: python -m src.main

      - name: Upload report artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: pubmed-report
          path: output/*.md